### ISSUE TITLE
ERROR: Missing packages. Make sure you're connected to the internet.

### ISSUE THREAD

**Issue by crstauf** [afragen/setup-phpunit#4]
<img width="1006" alt="Screen Shot 2021-11-09 at 19 47 50" src="https://user-images.githubusercontent.com/4573033/141029098-04ed5310-3f3f-4e64-9714-1e7c437188b2.png">

I'm obviously connected to the internet.

**Comment by crstauf** [comment]
More: https://community.localwp.com/t/local-lightning-phpunit-phpstorm/21854/9?u=crstauf

**Comment by afragen** [comment]
I'll have to take a closer look. Thanks for the reference to the the Local forum issue.

**Comment by afragen** [comment]
These are the packages that are required, which don't you have installed?

https://github.com/afragen/setup-phpunit/blob/f6b9f610016581059f145a8846618ec4678faddf/setup-phpunit.sh#L163

**Comment by crstauf** [comment]
@afragen Ahh, I didn't have `svn`. Thanks!

**Comment by afragen** [comment]
I think the issue may be that SVN is no longer bundled with macOS. I'll have to update that.

**Comment by afragen** [comment]
I did update to install SVN for macOS
