### ISSUE TITLE
Could not find `functions.php`

### ISSUE THREAD

**Issue by crstauf** [afragen/setup-phpunit#6]
After running `bash setup-phpunit.sh` and navigating to plugin with unit tests:

```
$ phpunit
Could not find /var/folders/hk/4slx_nm557x9mlqwlqjkkxsw0000gn/T/wordpress-tests-lib/includes/functions.php, have you run bin/install-wp-tests.sh ?
```

Does `install-wp-tests.sh` need to be run?

**Comment by afragen** [comment]
Your individual plugin needs to be scaffolded to run unit tests.

**Comment by crstauf** [comment]
It has already: `bin/install-wp-tests.sh` exists, but I was under the impression that this script does everything and is a replacement for `install-wp-tests.sh`, thus my question: does it need to be run?

**Comment by afragen** [comment]
You shouldn't need to run it. It should all be in the script.

**Comment by crstauf** [comment]
Understood. Does a write permissions issue seem likely in that case?

**Comment by afragen** [comment]
It's possible. That's usually supposed to be the /tmp directory.

**Comment by afragen** [comment]
I think you do need to run `install-wp-tests.php`. I think it's usually run from the bootstrap file.

**Comment by crstauf** [comment]
@afragen Where can I find `install-wp-tests.php`, and what's the bootstrap file?

**Comment by afragen** [comment]
https://developer.wordpress.org/cli/commands/scaffold/plugin/

**Comment by crstauf** [comment]
I'm not certain what changed, but it's working now.  ¯\\_(ツ)_/¯

Thanks for your help, @afragen! :cookie:
