### ISSUE TITLE
Permission issue for bash setup-phpunit.sh command

### ISSUE THREAD

**Issue by 1naveengiri** [afragen/setup-phpunit#7]
This command to run the script `bash setup-phpunit.sh` want me to have sudo access. 

so I am not sure if I am the only one who have that issue, otherwise please update the readME.md

Thanks for creating it.

**Comment by afragen** [comment]
It might be related to you folder permissions. I haven't seen the need for `sudo` before.

**Comment by 1naveengiri** [comment]
Yeah, I think so. 

Thanks, I will close it.
